"""
export_to_js.py
Reads synthetic_records.json and writes data.js as an ES module export.
"""

import json
import os

JSON_PATH = os.path.join(os.path.dirname(__file__), 'synthetic_records.json')
OUTPUT_PATH = os.path.join(os.path.dirname(__file__), 'data.js')


def format_record(record):
    """Format a single record as a JS object literal string."""
    lines = ['    {']
    for key, value in record.items():
        if value is None:
            lines.append(f'      {key}: null,')
        elif isinstance(value, bool):
            lines.append(f'      {key}: {"true" if value else "false"},')
        elif isinstance(value, float):
            lines.append(f'      {key}: {value},')
        elif isinstance(value, int):
            lines.append(f'      {key}: {value},')
        elif isinstance(value, list):
            if len(value) == 0:
                lines.append(f'      {key}: [],')
            else:
                items = ', '.join(f'"{v}"' for v in value)
                lines.append(f'      {key}: [{items}],')
        elif isinstance(value, str):
            escaped = value.replace('\\', '\\\\').replace('"', '\\"').replace("'", "\\'").replace('\n', '\\n').replace('\r', '\\r').replace('\t', '\\t')
            lines.append(f'      {key}: "{escaped}",')
        else:
            lines.append(f'      {key}: "{value}",')
    lines.append('    }')
    return '\n'.join(lines)


def main():
    print(f"Reading {JSON_PATH}...")
    with open(JSON_PATH, 'r', encoding='utf-8') as f:
        records = json.load(f)

    print(f"Writing {len(records)} records to {OUTPUT_PATH}...")

    with open(OUTPUT_PATH, 'w', encoding='utf-8') as f:
        f.write('// Auto-generated synthetic ARB/ARG monitoring data\n')
        f.write('// Generated by export_to_js.py\n\n')
        f.write('export const syntheticRecords = [\n')
        for i, record in enumerate(records):
            formatted = format_record(record)
            if i < len(records) - 1:
                f.write(formatted + ',\n')
            else:
                f.write(formatted + '\n')
        f.write('];\n')

    print("Done.")


if __name__ == '__main__':
    main()
