// mock_data.js
// Exports 20 hardcoded canonical records with realistic values for NJ-WARMD development

export const syntheticRecords = [
  {
    record_id: "WWTP_09_20250415_NDM_1_1",
    site_id: "WWTP_09",
    site_type: "WWTP",
    county: "Essex",
    municipality: "Newark City",
    lat: 40.712792491550026,
    lng: -74.13445798816387,
    sample_date: "2025-04-15",
    device_type: "PCR",
    device_id: "Well_A1",
    submitted_by: "DEP Operator",
    target_gene: "NDM-1",
    aro_number: "ARO:3000590",
    canonical_name: "NDM-1",
    drug_class: "carbapenem",
    mechanism: "antibiotic inactivation",
    detected: true,
    detection_status: "CONFIRMED",
    ct_value: 22.5,
    concentration: 5400,
    concentration_unit: "COPIES_PER_ML",
    confidence_score: 0.98,
    raw_target_name: "NDM-1",
    raw_device_fields: "{}",
    upload_timestamp: "2025-04-15T14:00:00Z",
    normalization_timestamp: "2025-04-15T14:05:00Z",
    validation_status: "ACCEPTED",
    validation_flags: [],
    compliance_status: "compliant",
    compliance_note: "Site is compliant.",
    clearance_achieved: false,
    data_quality_flag: "PASS"
  },
  {
    record_id: "WWTP_09_20250415_KPC_2_2",
    site_id: "WWTP_09",
    site_type: "WWTP",
    county: "Essex",
    municipality: "Newark City",
    lat: 40.712792491550026,
    lng: -74.13445798816387,
    sample_date: "2025-04-15",
    device_type: "PCR",
    device_id: "Well_A2",
    submitted_by: "DEP Operator",
    target_gene: "KPC-2",
    aro_number: "ARO:3003510",
    canonical_name: "KPC-2",
    drug_class: "carbapenem",
    mechanism: "antibiotic inactivation",
    detected: true,
    detection_status: "CONFIRMED",
    ct_value: 24.1,
    concentration: 3100,
    concentration_unit: "COPIES_PER_ML",
    confidence_score: 0.97,
    raw_target_name: "KPC-2",
    raw_device_fields: "{}",
    upload_timestamp: "2025-04-15T14:00:00Z",
    normalization_timestamp: "2025-04-15T14:05:00Z",
    validation_status: "ACCEPTED",
    validation_flags: [],
    compliance_status: "compliant",
    compliance_note: "Site is compliant.",
    clearance_achieved: false,
    data_quality_flag: "PASS"
  },
  {
    record_id: "HOSPITAL_01_20250510_mecA_3",
    site_id: "HOSPITAL_01",
    site_type: "HOSPITAL",
    county: "Bergen",
    municipality: "Paramus",
    lat: 40.9458,
    lng: -74.0628,
    sample_date: "2025-05-10",
    device_type: "BIOSENSOR",
    device_id: "CH1",
    submitted_by: "Hospital Staff",
    target_gene: "mecA",
    aro_number: "ARO:3000690",
    canonical_name: "mecA",
    drug_class: "methicillin",
    mechanism: "antibiotic target replacement",
    detected: true,
    detection_status: "CONFIRMED",
    ct_value: null,
    concentration: 850,
    concentration_unit: "RFU",
    confidence_score: 0.95,
    raw_target_name: "mecA",
    raw_device_fields: "{}",
    upload_timestamp: "2025-05-10T11:00:00Z",
    normalization_timestamp: "2025-05-10T11:15:00Z",
    validation_status: "ACCEPTED",
    validation_flags: [],
    compliance_status: "compliant",
    compliance_note: "Site is compliant.",
    clearance_achieved: false,
    data_quality_flag: "PASS"
  },
  {
    record_id: "SURFACE_WATER_01_20250601_CTX_M_15_4",
    site_id: "SURFACE_WATER_01",
    site_type: "SURFACE_WATER",
    county: "Passaic",
    municipality: "Paterson",
    lat: 40.9164277,
    lng: -74.1819827,
    sample_date: "2025-06-01",
    device_type: "METAGENOMICS",
    device_id: "SRR102931",
    submitted_by: "Field Tech",
    target_gene: "CTX-M-15",
    aro_number: "ARO:3000590",
    canonical_name: "CTX-M-15",
    drug_class: "cephalosporin",
    mechanism: "antibiotic inactivation",
    detected: true,
    detection_status: "CONFIRMED",
    ct_value: null,
    concentration: 89.2,
    concentration_unit: "RPM",
    confidence_score: 0.92,
    raw_target_name: "CTX-M-15",
    raw_device_fields: "{}",
    upload_timestamp: "2025-06-01T16:00:00Z",
    normalization_timestamp: "2025-06-01T16:20:00Z",
    validation_status: "ACCEPTED",
    validation_flags: [],
    compliance_status: "compliant",
    compliance_note: "Site is compliant.",
    clearance_achieved: false,
    data_quality_flag: "PASS"
  },
  {
    record_id: "AGRICULTURAL_01_20250615_mcr_1_5",
    site_id: "AGRICULTURAL_01",
    site_type: "AGRICULTURAL",
    county: "Salem",
    municipality: "Woodstown",
    lat: 39.591,
    lng: -75.467,
    sample_date: "2025-06-15",
    device_type: "MICROFLUIDIC",
    device_id: "MF-01",
    submitted_by: "Ag Investigator",
    target_gene: "mcr-1",
    aro_number: "ARO:3003689",
    canonical_name: "mcr-1",
    drug_class: "peptide antibiotic",
    mechanism: "antibiotic target alteration",
    detected: true,
    detection_status: "CONFIRMED",
    ct_value: null,
    concentration: 120.5,
    concentration_unit: "COPIES_PER_ML",
    confidence_score: 0.94,
    raw_target_name: "mcr-1",
    raw_device_fields: "{}",
    upload_timestamp: "2025-06-15T09:00:00Z",
    normalization_timestamp: "2025-06-15T09:10:00Z",
    validation_status: "ACCEPTED",
    validation_flags: [],
    compliance_status: "compliant",
    compliance_note: "Site is compliant.",
    clearance_achieved: false,
    data_quality_flag: "PASS"
  },
  {
    record_id: "WWTP_01_20250701_vanA_6",
    site_id: "WWTP_01",
    site_type: "WWTP",
    county: "Bergen",
    municipality: "Little Ferry Boro",
    lat: 40.83266670967254,
    lng: -74.03232824673903,
    sample_date: "2025-07-01",
    device_type: "PCR",
    device_id: "Well_B1",
    submitted_by: "DEP Operator",
    target_gene: "vanA",
    aro_number: "ARO:3000010",
    canonical_name: "vanA",
    drug_class: "glycopeptide antibiotic",
    mechanism: "antibiotic target alteration",
    detected: false,
    detection_status: "NOT_DETECTED",
    ct_value: 40.0,
    concentration: 0,
    concentration_unit: "COPIES_PER_ML",
    confidence_score: 0.88,
    raw_target_name: "vanA",
    raw_device_fields: "{}",
    upload_timestamp: "2025-07-01T14:00:00Z",
    normalization_timestamp: "2025-07-01T14:05:00Z",
    validation_status: "ACCEPTED",
    validation_flags: [],
    compliance_status: "compliant",
    compliance_note: "Site is compliant.",
    clearance_achieved: true,
    data_quality_flag: "PASS"
  },
  {
    record_id: "WWTP_02_20250702_tetM_7",
    site_id: "WWTP_02",
    site_type: "WWTP",
    county: "Monmouth",
    municipality: "Allentown Boro",
    lat: 40.177499428220045,
    lng: -74.59669003046301,
    sample_date: "2025-07-02",
    device_type: "PCR",
    device_id: "Well_B2",
    submitted_by: "DEP Operator",
    target_gene: "tetM",
    aro_number: "ARO:3000186",
    canonical_name: "tetM",
    drug_class: "tetracycline antibiotic",
    mechanism: "antibiotic target protection",
    detected: true,
    detection_status: "CONFIRMED",
    ct_value: 19.5,
    concentration: 12000,
    concentration_unit: "COPIES_PER_ML",
    confidence_score: 0.99,
    raw_target_name: "tetM",
    raw_device_fields: "{}",
    upload_timestamp: "2025-07-02T14:00:00Z",
    normalization_timestamp: "2025-07-02T14:05:00Z",
    validation_status: "ACCEPTED",
    validation_flags: [],
    compliance_status: "compliant",
    compliance_note: "Site is compliant.",
    clearance_achieved: false,
    data_quality_flag: "PASS"
  },
  {
    record_id: "HOSPITAL_02_20250703_aac_3_IIa_8",
    site_id: "HOSPITAL_02",
    site_type: "HOSPITAL",
    county: "Bergen",
    municipality: "Hackensack",
    lat: 40.8872,
    lng: -74.0565,
    sample_date: "2025-07-03",
    device_type: "BIOSENSOR",
    device_id: "CH2",
    submitted_by: "Hospital Staff",
    target_gene: "aac(3)-IIa",
    aro_number: "ARO:3000167",
    canonical_name: "aac(3)-IIa",
    drug_class: "aminoglycoside antibiotic",
    mechanism: "antibiotic inactivation",
    detected: true,
    detection_status: "PROBABLE",
    ct_value: null,
    concentration: 450,
    concentration_unit: "RFU",
    confidence_score: 0.91,
    raw_target_name: "aac(3)-IIa",
    raw_device_fields: "{}",
    upload_timestamp: "2025-07-03T11:00:00Z",
    normalization_timestamp: "2025-07-03T11:15:00Z",
    validation_status: "ACCEPTED",
    validation_flags: [],
    compliance_status: "compliant",
    compliance_note: "Site is compliant.",
    clearance_achieved: false,
    data_quality_flag: "PASS"
  },
  {
    record_id: "SURFACE_WATER_02_20250704_qnrS1_9",
    site_id: "SURFACE_WATER_02",
    site_type: "SURFACE_WATER",
    county: "Middlesex",
    municipality: "New Brunswick",
    lat: 40.4888119,
    lng: -74.3966225,
    sample_date: "2025-07-04",
    device_type: "METAGENOMICS",
    device_id: "SRR102932",
    submitted_by: "Field Tech",
    target_gene: "qnrS1",
    aro_number: "ARO:3000448",
    canonical_name: "qnrS1",
    drug_class: "fluoroquinolone",
    mechanism: "antibiotic target protection",
    detected: false,
    detection_status: "NOT_DETECTED",
    ct_value: null,
    concentration: 0,
    concentration_unit: "RPM",
    confidence_score: 0.75,
    raw_target_name: "qnrS1",
    raw_device_fields: "{}",
    upload_timestamp: "2025-07-04T16:00:00Z",
    normalization_timestamp: "2025-07-04T16:20:00Z",
    validation_status: "ACCEPTED",
    validation_flags: [],
    compliance_status: "compliant",
    compliance_note: "Site is compliant.",
    clearance_achieved: true,
    data_quality_flag: "PASS"
  },
  {
    record_id: "AGRICULTURAL_02_20250705_tetA_10",
    site_id: "AGRICULTURAL_02",
    site_type: "AGRICULTURAL",
    county: "Cumberland",
    municipality: "Bridgeton",
    lat: 39.3720,
    lng: -75.1140,
    sample_date: "2025-07-05",
    device_type: "MICROFLUIDIC",
    device_id: "MF-02",
    submitted_by: "Ag Investigator",
    target_gene: "tetA",
    aro_number: "ARO:3000196",
    canonical_name: "tetA",
    drug_class: "tetracycline antibiotic",
    mechanism: "antibiotic efflux",
    detected: true,
    detection_status: "CONFIRMED",
    ct_value: null,
    concentration: 320.1,
    concentration_unit: "COPIES_PER_ML",
    confidence_score: 0.96,
    raw_target_name: "tetA",
    raw_device_fields: "{}",
    upload_timestamp: "2025-07-05T09:00:00Z",
    normalization_timestamp: "2025-07-05T09:10:00Z",
    validation_status: "ACCEPTED",
    validation_flags: [],
    compliance_status: "compliant",
    compliance_note: "Site is compliant.",
    clearance_achieved: false,
    data_quality_flag: "PASS"
  },
  {
    record_id: "WWTP_03_20250706_OXA_48_11",
    site_id: "WWTP_03",
    site_type: "WWTP",
    county: "Morris",
    municipality: "Chatham Twp",
    lat: 40.71287855193237,
    lng: -74.40931824109977,
    sample_date: "2025-07-06",
    device_type: "PCR",
    device_id: "Well_C1",
    submitted_by: "DEP Operator",
    target_gene: "OXA-48",
    aro_number: "ARO:3001799",
    canonical_name: "OXA-48",
    drug_class: "carbapenem",
    mechanism: "antibiotic inactivation",
    detected: false,
    detection_status: "NOT_DETECTED",
    ct_value: 45.0,
    concentration: 0,
    concentration_unit: "COPIES_PER_ML",
    confidence_score: 0.82,
    raw_target_name: "OXA-48",
    raw_device_fields: "{}",
    upload_timestamp: "2025-07-06T14:00:00Z",
    normalization_timestamp: "2025-07-06T14:05:00Z",
    validation_status: "ACCEPTED",
    validation_flags: [],
    compliance_status: "compliant",
    compliance_note: "Site is compliant.",
    clearance_achieved: true,
    data_quality_flag: "PASS"
  },
  {
    record_id: "HOSPITAL_03_20250707_mecA_12",
    site_id: "HOSPITAL_03",
    site_type: "HOSPITAL",
    county: "Morris",
    municipality: "Morristown",
    lat: 40.7891,
    lng: -74.4682,
    sample_date: "2025-07-07",
    device_type: "BIOSENSOR",
    device_id: "CH3",
    submitted_by: "Hospital Staff",
    target_gene: "mecA",
    aro_number: "ARO:3000690",
    canonical_name: "mecA",
    drug_class: "methicillin",
    mechanism: "antibiotic target replacement",
    detected: true,
    detection_status: "CONFIRMED",
    ct_value: null,
    concentration: 620,
    concentration_unit: "RFU",
    confidence_score: 0.94,
    raw_target_name: "mecA",
    raw_device_fields: "{}",
    upload_timestamp: "2025-07-07T11:00:00Z",
    normalization_timestamp: "2025-07-07T11:15:00Z",
    validation_status: "ACCEPTED",
    validation_flags: [],
    compliance_status: "compliant",
    compliance_note: "Site is compliant.",
    clearance_achieved: false,
    data_quality_flag: "PASS"
  },
  {
    record_id: "SURFACE_WATER_03_20250708_CTX_M_14_13",
    site_id: "SURFACE_WATER_03",
    site_type: "SURFACE_WATER",
    county: "Mercer",
    municipality: "Trenton",
    lat: 40.2277798,
    lng: -74.7585779,
    sample_date: "2025-07-08",
    device_type: "METAGENOMICS",
    device_id: "SRR102933",
    submitted_by: "Field Tech",
    target_gene: "CTX-M-14",
    aro_number: "ARO:3000590",
    canonical_name: "CTX-M-14",
    drug_class: "cephalosporin",
    mechanism: "antibiotic inactivation",
    detected: true,
    detection_status: "PROBABLE",
    ct_value: null,
    concentration: 42.1,
    concentration_unit: "RPM",
    confidence_score: 0.89,
    raw_target_name: "CTX-M-14",
    raw_device_fields: "{}",
    upload_timestamp: "2025-07-08T16:00:00Z",
    normalization_timestamp: "2025-07-08T16:20:00Z",
    validation_status: "ACCEPTED",
    validation_flags: [],
    compliance_status: "compliant",
    compliance_note: "Site is compliant.",
    clearance_achieved: false,
    data_quality_flag: "PASS"
  },
  {
    record_id: "AGRICULTURAL_03_20250709_vanB_14",
    site_id: "AGRICULTURAL_03",
    site_type: "AGRICULTURAL",
    county: "Hunterdon",
    municipality: "Flemington",
    lat: 40.5560,
    lng: -74.8230,
    sample_date: "2025-07-09",
    device_type: "MICROFLUIDIC",
    device_id: "MF-03",
    submitted_by: "Ag Investigator",
    target_gene: "vanB",
    aro_number: "ARO:3000011",
    canonical_name: "vanB",
    drug_class: "glycopeptide antibiotic",
    mechanism: "antibiotic target alteration",
    detected: false,
    detection_status: "NOT_DETECTED",
    ct_value: null,
    concentration: 0,
    concentration_unit: "COPIES_PER_ML",
    confidence_score: 0.79,
    raw_target_name: "vanB",
    raw_device_fields: "{}",
    upload_timestamp: "2025-07-09T09:00:00Z",
    normalization_timestamp: "2025-07-09T09:10:00Z",
    validation_status: "ACCEPTED",
    validation_flags: [],
    compliance_status: "compliant",
    compliance_note: "Site is compliant.",
    clearance_achieved: true,
    data_quality_flag: "PASS"
  },
  {
    record_id: "WWTP_04_20250710_TEM_1_15",
    site_id: "WWTP_04",
    site_type: "WWTP",
    county: "Morris",
    municipality: "Chatham Twp",
    lat: 40.72081312892862,
    lng: -74.41862675521918,
    sample_date: "2025-07-10",
    device_type: "PCR",
    device_id: "Well_D1",
    submitted_by: "DEP Operator",
    target_gene: "TEM-1",
    aro_number: "ARO:3000413",
    canonical_name: "TEM-1",
    drug_class: "penicillin",
    mechanism: "antibiotic inactivation",
    detected: true,
    detection_status: "CONFIRMED",
    ct_value: 23.4,
    concentration: 4800,
    concentration_unit: "COPIES_PER_ML",
    confidence_score: 0.98,
    raw_target_name: "TEM-1",
    raw_device_fields: "{}",
    upload_timestamp: "2025-07-10T14:00:00Z",
    normalization_timestamp: "2025-07-10T14:05:00Z",
    validation_status: "ACCEPTED",
    validation_flags: [],
    compliance_status: "compliant",
    compliance_note: "Site is compliant.",
    clearance_achieved: false,
    data_quality_flag: "PASS"
  },
  {
    record_id: "HOSPITAL_04_20250711_mecC_16",
    site_id: "HOSPITAL_04",
    site_type: "HOSPITAL",
    county: "Passaic",
    municipality: "Paterson",
    lat: 40.9022,
    lng: -74.1565,
    sample_date: "2025-07-11",
    device_type: "BIOSENSOR",
    device_id: "CH4",
    submitted_by: "Hospital Staff",
    target_gene: "mecC",
    aro_number: "ARO:3001213",
    canonical_name: "mecC",
    drug_class: "methicillin",
    mechanism: "antibiotic target replacement",
    detected: false,
    detection_status: "NOT_DETECTED",
    ct_value: null,
    concentration: 0,
    concentration_unit: "RFU",
    confidence_score: 0.81,
    raw_target_name: "mecC",
    raw_device_fields: "{}",
    upload_timestamp: "2025-07-11T11:00:00Z",
    normalization_timestamp: "2025-07-11T11:15:00Z",
    validation_status: "ACCEPTED",
    validation_flags: [],
    compliance_status: "compliant",
    compliance_note: "Site is compliant.",
    clearance_achieved: true,
    data_quality_flag: "PASS"
  },
  {
    record_id: "SURFACE_WATER_04_20250712_SHV_12_17",
    site_id: "SURFACE_WATER_04",
    site_type: "SURFACE_WATER",
    county: "Bergen",
    municipality: "Hackensack",
    lat: 40.925305,
    lng: -74.0329398,
    sample_date: "2025-07-12",
    device_type: "METAGENOMICS",
    device_id: "SRR102934",
    submitted_by: "Field Tech",
    target_gene: "SHV-12",
    aro_number: "ARO:3000590",
    canonical_name: "SHV-12",
    drug_class: "cephalosporin",
    mechanism: "antibiotic inactivation",
    detected: true,
    detection_status: "CONFIRMED",
    ct_value: null,
    concentration: 110.8,
    concentration_unit: "RPM",
    confidence_score: 0.93,
    raw_target_name: "SHV-12",
    raw_device_fields: "{}",
    upload_timestamp: "2025-07-12T16:00:00Z",
    normalization_timestamp: "2025-07-12T16:20:00Z",
    validation_status: "ACCEPTED",
    validation_flags: [],
    compliance_status: "compliant",
    compliance_note: "Site is compliant.",
    clearance_achieved: false,
    data_quality_flag: "PASS"
  },
  {
    record_id: "AGRICULTURAL_04_20250713_tetX_18",
    site_id: "AGRICULTURAL_04",
    site_type: "AGRICULTURAL",
    county: "Middlesex",
    municipality: "North Brunswick",
    lat: 40.4400,
    lng: -74.4500,
    sample_date: "2025-07-13",
    device_type: "MICROFLUIDIC",
    device_id: "MF-04",
    submitted_by: "Ag Investigator",
    target_gene: "tetX",
    aro_number: "ARO:3000205",
    canonical_name: "tetX",
    drug_class: "tetracycline antibiotic",
    mechanism: "antibiotic inactivation",
    detected: true,
    detection_status: "CONFIRMED",
    ct_value: null,
    concentration: 405.3,
    concentration_unit: "COPIES_PER_ML",
    confidence_score: 0.97,
    raw_target_name: "tetX",
    raw_device_fields: "{}",
    upload_timestamp: "2025-07-13T09:00:00Z",
    normalization_timestamp: "2025-07-13T09:10:00Z",
    validation_status: "ACCEPTED",
    validation_flags: [],
    compliance_status: "compliant",
    compliance_note: "Site is compliant.",
    clearance_achieved: false,
    data_quality_flag: "PASS"
  },
  {
    record_id: "WWTP_05_20250714_VIM_1_19",
    site_id: "WWTP_05",
    site_type: "WWTP",
    county: "Hunterdon",
    municipality: "Clinton Town",
    lat: 40.62626824362079,
    lng: -74.91100390813007,
    sample_date: "2025-07-14",
    device_type: "PCR",
    device_id: "Well_E1",
    submitted_by: "DEP Operator",
    target_gene: "VIM-1",
    aro_number: "ARO:3000855",
    canonical_name: "VIM-1",
    drug_class: "carbapenem",
    mechanism: "antibiotic inactivation",
    detected: false,
    detection_status: "NOT_DETECTED",
    ct_value: 41.5,
    concentration: 0,
    concentration_unit: "COPIES_PER_ML",
    confidence_score: 0.85,
    raw_target_name: "VIM-1",
    raw_device_fields: "{}",
    upload_timestamp: "2025-07-14T14:00:00Z",
    normalization_timestamp: "2025-07-14T14:05:00Z",
    validation_status: "ACCEPTED",
    validation_flags: [],
    compliance_status: "compliant",
    compliance_note: "Site is compliant.",
    clearance_achieved: true,
    data_quality_flag: "PASS"
  },
  {
    record_id: "HOSPITAL_05_20250715_mecA_20",
    site_id: "HOSPITAL_05",
    site_type: "HOSPITAL",
    county: "Middlesex",
    municipality: "New Brunswick",
    lat: 40.4933,
    lng: -74.4511,
    sample_date: "2025-07-15",
    device_type: "BIOSENSOR",
    device_id: "CH5",
    submitted_by: "Hospital Staff",
    target_gene: "mecA",
    aro_number: "ARO:3000690",
    canonical_name: "mecA",
    drug_class: "methicillin",
    mechanism: "antibiotic target replacement",
    detected: true,
    detection_status: "CONFIRMED",
    ct_value: null,
    concentration: 910,
    concentration_unit: "RFU",
    confidence_score: 0.96,
    raw_target_name: "mecA",
    raw_device_fields: "{}",
    upload_timestamp: "2025-07-15T11:00:00Z",
    normalization_timestamp: "2025-07-15T11:15:00Z",
    validation_status: "ACCEPTED",
    validation_flags: [],
    compliance_status: "compliant",
    compliance_note: "Site is compliant.",
    clearance_achieved: false,
    data_quality_flag: "PASS"
  }
];
